-- 증폭용 시퀀스 테이블. 1세대 = 원본 313전시/229전시장 한 벌.
-- 목표 볼륨 = 313 × 세대수 (100k≈320 · 500k≈1597 · 1M≈3195)
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS lt_seq (n INT NOT NULL PRIMARY KEY) ENGINE=InnoDB;

INSERT IGNORE INTO lt_seq (n)
SELECT a.d + b.d*10 + c.d*100 + e.d*1000
FROM (SELECT 0 d UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4
      UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) a
CROSS JOIN (SELECT 0 d UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4
      UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) b
CROSS JOIN (SELECT 0 d UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4
      UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) c
CROSS JOIN (SELECT 0 d UNION SELECT 1 UNION SELECT 2 UNION SELECT 3) e
WHERE a.d + b.d*10 + c.d*100 + e.d*1000 BETWEEN 1 AND 3200;

-- 원본 경계를 한 번만 기록해 둔다(reset·증폭이 이 값을 기준으로 원본을 보존한다).
CREATE TABLE IF NOT EXISTS lt_base (
    t VARCHAR(32) NOT NULL PRIMARY KEY,
    max_id BIGINT NOT NULL
) ENGINE=InnoDB;

INSERT IGNORE INTO lt_base (t, max_id) VALUES
    ('exhibitions',       (SELECT COALESCE(MAX(id),0) FROM exhibitions)),
    ('exhibition_place',  (SELECT COALESCE(MAX(id),0) FROM exhibition_place)),
    ('exhibition_detail', (SELECT COALESCE(MAX(id),0) FROM exhibition_detail)),
    ('exhibition_genre',  (SELECT COALESCE(MAX(id),0) FROM exhibition_genre));

SELECT t, max_id FROM lt_base;
